# --------------------------------------
# Fluid 个性化定制
# --------------------------------------


index:
  banner_img: /img/background.png
  banner_text: "Via NoGamble"
  banner_parallax: true # 开启视差滚动效果
  scroll_down_arrow: true # 开启向下滚动箭头
  slogan:
    enable: true
    text: "This is Via NoGamble." # 在这里填入你的副标题
    api:
      enable: false # 暂时关闭 API，先确保显示你自己的文字
  post_url_target: _self # 设置首页文章链接打开方式，_self 为当前窗口打开，_blank 为新窗口打开
  auto_excerpt:
    enable: true


fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 100 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果

navbar:
  blog_title: "Via NoGamble"
  bg_alpha: 0.0
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill', name: 'Home' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: 'Tags' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill', name: 'Archives' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill', name: 'Categories' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: 'Contact' }

dark_mode:
  enable: true
  default: light

open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

favicon: /img/favicon.png

about:
  avatar: /img/favicon.png
  name: "NoGamble"
  intro: "UESTC CS Junior | Forza Milan!"

category:
  enable: true
  banner_img: /img/background.png
  slogan:
    enable: true
    text: "Categories."
  api:
      enable: false

tag:
  enable: true
  banner_img: /img/background.png
  slogan:
    enable: true
    text: "Tags."
  api:
      enable: false


archive:
  enable: true
  banner_img: /img/background.png
  slogan:
    enable: true
    text: "Archives."
  api:
      enable: false

custom_css: [/css/custom.css]
custom_js: [/js/custom.js]